export enum KeyCode {
  ArrowUp = "ArrowUp",
  ArrowDown = "ArrowDown",
  ArrowLeft = "ArrowLeft",
  ArrowRight = "ArrowRight",
  KeyC = "KeyC",
  KeyH = "KeyH",
  KeyM = "KeyM",
  KeyR = "KeyR",
  KeyV = "KeyV",
  Escape = "Escape",
  Tab = "Tab",
  Enter = "Enter",
  Backspace = "Backspace",
  ShiftLeft = "ShiftLeft",
  ShiftRight = "ShiftRight",
}
