export enum KeyCode {
  ArrowUp = "ArrowUp",
  ArrowDown = "ArrowDown",
  ArrowLeft = "ArrowLeft",
  ArrowRight = "ArrowRight",
  KeyC = "c",
  KeyH = "h",
  KeyL = "l",
  KeyM = "m",
  KeyR = "r",
  KeyV = "v",
  KeyZ = "z",
  Escape = "Escape",
  Tab = "Tab",
  Backspace = "Backspace",
  Shift = "Shift",
  ShiftLeft = "ShiftLeft",
  ShiftRight = "ShiftRight",
}
